### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by strivedge** [signinit/injectable-development-tutorial#2]
I'm new in react js. I have reactJs project with set of different environment like production development.
in package.json file script like this
"scripts": {
"start:development": "env-cmd -e development react-scripts start",
"start:sandbox": "env-cmd -e sandbox react-scripts start",
"start:production": "env-cmd -e production react-scripts start",
"start:local": "env-cmd -e local react-scripts start",
"build": "./build-remote-copy.sh",
"test": "react-scripts test --env=jsdom",
"eject": "react-scripts eject"
}
now i want to run this project.
how can i run this project please help me..

**Comment by signinit** [comment]
Sorry but I don't think your issue has any relation to this project.
